// wevocal-lib（TypeScript 側）: WeVocalSynth と WeVocalExtractor で共通に使う、音声ファイルの読み込みと書き出し、再生の開始と停止、波形の表示の土台
export type { Clip, Range } from './types'
export { ALGORITHM_ID, ALGORITHM_NAMES, type Algorithm } from './algorithm'
export { AUDIO_ACCEPT, decodeFile, readFile, mp4SampleRate } from './decode'
export { encodeWav, downloadWav, downloadBlob, type WavFormat } from './wav'
export { exportAudio, EXPORT_EXT, EXPORT_MIME, type ExportFormat, type ExportOptions } from './export/exportAudio'
export { AAC_SAMPLE_RATES, BITRATES, MP3_SAMPLE_RATES, OPUS_SAMPLE_RATE, canEncodeAac, canEncodeOpus, isLossy, kbpsForSize, type LossyFormat } from './export/formats'
export { prepareClip } from './export/prepare'
export { startContext, suspendContext, configurePlayback, type PlaybackOptions } from './playback'
export { canSelectOutput, setOutputDevice, listOutputDevices, revealDeviceLabels, type OutputDevice } from './outputDevice'
export { canRecord, listInputDevices, openInput, startRecording, type InputDevice, type InputOptions, type Recording } from './record'
export * from './waveform'
export { WVSP_EXT, WVSP_VERSION, isWvspFile, readWvsp, writeWvsp, WvspError, type WvspHeader, type WvspTrack } from './wvsp'
// トラックのエフェクト（EQ、フェーダー）。WeVocalSynth の src/effects/ から移した
export type { Effect, LiveEffect } from './effects/types'
export * from './effects/eq'
export * from './effects/fader'
export { DEFAULT_SILENCE, findSounds, type SilenceOptions } from './silence'
export { tempoSegments, segmentAt, bpmAt, beatsIn, nearestBeat, stepBeat, type TempoSegment, type Beat, type BaseTempo, type TempoMarker } from './tempoMap'
export { toFrames, GAIN_RAMP_SEC, mapGain, gainRange, fadeRange, normalizeRange, finishClip, type FinishOptions } from './clipEdit'
